exclude:
- .*/fresfdsfdsfds/fdsfdsfdsfdsfds/fdsfdsfdsfdsfsdfds/fdsfdsfdsfdsfsdfsd/fdsfdsfdsfdsfds/fdsfdsfdsfdsfsd/fdsfdsfdsfdsfsd/fdsfdsfdsfdsfdsf/fdsfdsfdsfsdfsd/fdsfsdfdsfsd/fdsfdsfsdfdsfds/fdsfdsfdsfdsfsd/newrelic[.]js
component_depth: 1
languages:
- java
