exclude:
- .*/fdsfdsfdsf/fdsfdsfddsfds/gfdsgfdgfd/gfdgfdgfdgfdgdfgqgfdsagfs/gasfgdfsagasgasgsagasg/gdsagdsasgddsagasdgasgdasg/gasgsadgasgasgsag/gsadgdsagasdgasgsag/gasdgsagdsagasdgsag/gdasgdsagsagsagsag/gadsgdasdgagsdnewrelic[.]js
component_depth: 1
languages:
- java
