exclude:
- .*/fdsfdsfdsf/fdsfdsfdsfsdfsfsdfds/fdsfdsfdsfsdfdsfsdfds/fdsfdsfdsfdsfdsfdsfsdfds/fdsfsdfdsfsdfdsfdsfsfdsfds/fdsfdsfdsfdsfdsfsd/fdsfdsfdsfdsfsd/fdsfdsfdsfdsfdsfs/fdsfdsfdsfdsfdsfds/fdsfdsfdsfsdfdsfsdfsd/0fdsfdsfdsfdsfdsfds/fdsfdsfddsfds/newrelic[.]js
component_depth: 1
languages:
- java
