exclude:
- .*/newrelic/fdsfdsfsdfds/fdsfsdfdsfdsfsd/fdsfdsfdsfdsfds/fdsfdsfdsfsdf/fdsfdsfdsfsfdse/fdsfdsfdsf/fdsfdsfdsfsfdsf/fdsfdsfdsfdsfdsfdsfds/fdsfdsfdsfdsfdsfd/fdsfdsfdsfdsfdsfds/fdsfdsfdsfdsfdfdsfdsfds[.]js
component_depth: 1
languages:
- java
